<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>FriendlyNoclip</AssemblyName>
    <LangVerson>10.0</LangVersion>
    <GameDir>..\gamedir</GameDir>
    <Il2cppDir>..\gamedir\MelonLoader\Il2CppAssemblies</Il2cppDir>
    <MelonLoaderDir>..\gamedir\MelonLoader\net6</MelonLoaderDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(MelonLoaderDir)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
